/*
 * CHIPDevicePlatformConfig.h
 * Platform configuration for Raspberry Pi Pico W Matter port
 */

#pragma once

// Platform capabilities
#define CHIP_DEVICE_PLATFORM_PICO 1
#define CHIP_DEVICE_CONFIG_ENABLE_WIFI 1
#define CHIP_DEVICE_CONFIG_ENABLE_THREAD 0
#define CHIP_DEVICE_CONFIG_ENABLE_ETHERNET 0

// Network configuration
#define CHIP_DEVICE_CONFIG_WIFI_STATION_IF_NAME "wlan0"
#define CHIP_DEVICE_CONFIG_ENABLE_WIFI_TELEMETRY 0
#define CHIP_DEVICE_CONFIG_ENABLE_WIFI_AP 0

// Device identification
#define CHIP_DEVICE_CONFIG_DEVICE_VENDOR_ID 0xFFF1
#define CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_ID 0x8001
#define CHIP_DEVICE_CONFIG_DEVICE_HARDWARE_VERSION 1
#define CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION 1
#define CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING "1.0"
#define CHIP_DEVICE_CONFIG_DEVICE_VENDOR_NAME "Viking Bio"
#define CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_NAME "Viking Bio 20 Matter Bridge"

// Commissioning configuration
#define CHIP_DEVICE_CONFIG_USE_TEST_SETUP_DISCRIMINATOR 0x0F00
#define CHIP_DEVICE_CONFIG_USE_TEST_SETUP_PIN_CODE 20202021
#define CHIP_DEVICE_CONFIG_USE_TEST_PAIRING_CODE "MT:Y.K9042C00KA0648G00"

// Memory and performance
#define CHIP_DEVICE_CONFIG_ENABLE_EXTENDED_DISCOVERY 1
#define CHIP_DEVICE_CONFIG_ENABLE_DNSSD 1
#define CHIP_DEVICE_CONFIG_ENABLE_COMMISSIONER_DISCOVERY 0

// Storage configuration
#define CHIP_DEVICE_CONFIG_PERSISTED_STORAGE_KEY_TYPE const char *
#define CHIP_DEVICE_CONFIG_PERSISTED_STORAGE_MAX_KEY_LENGTH 16
#define CHIP_DEVICE_CONFIG_PERSISTED_STORAGE_MAX_VALUE_LENGTH 256

// Security
#define CHIP_DEVICE_CONFIG_ENABLE_JUST_IN_TIME_PROVISIONING 0
#define CHIP_DEVICE_CONFIG_ENABLE_TEST_SETUP_PARAMS 1

// Event logging
#define CHIP_DEVICE_CONFIG_EVENT_LOGGING_UTC_TIMESTAMPS 1
#define CHIP_DEVICE_CONFIG_EVENT_LOGGING_NUM_EXTERNAL_CALLBACKS 2
#define CHIP_DEVICE_CONFIG_EVENT_LOGGING_EXTERNAL_EVENT_SUPPORT 1

// Platform-specific limits
#define CHIP_CONFIG_MAX_EXCHANGE_CONTEXTS 8
#define CHIP_CONFIG_MAX_BINDINGS 8
#define CHIP_CONFIG_MAX_FABRICS 5
#define CHIP_CONFIG_MAX_SESSION_KEYS 8
